1024pix/pix-360

- app/controllers/encryption_controller.rb
- config/routes.rb
- test/controllers/encryption_controller_test.rb
La supression de la page home_private n'a pas entièrement réalisée.
Vérification de la supression et redirection sur la page root
- Se connecter
- Remplir le formulaire de mdp
- Constater la redirection vers la page index
> [BUGFIX] Suppression de la page home_private

- .gitignore
- Dockerfile
Utilisation de la dernière version de ruby pour créer l'image de l'application
Forcer utilisation de ruby 3.0.2
> [INFRA] Fixer la version de ruby dans le Dockerfile

- app/assets/stylesheets/encryption.scss
- app/views/encryption/edit.html.erb
- app/views/encryption/index.html.erb
Création du design de la page encryption
Utilisation du scss pour améliorer le design
https://pfe-pix-360-pr21.osc-fr1.scalingo.io/users/sign_in
> [FEATURE] Amélioration du design de la page encryption

- .gitignore
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/globals/_colors.scss
- app/assets/stylesheets/navbar.scss
- app/controllers/application_controller.rb
- app/controllers/encryption_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/application.html.erb
On veut pouvoir naviguer sur les différentes pages de l'appli
Ajout d'un partial `_navbar` accessible depuis toute les pages de l'appli (à condition d'être connecté).
Pour l'instant cette navbar permet d'accéder à `/feedbacks`, `/feedbacks/new`, `/users/edit`, `/encryption/edit` et `/users/sign_out`
N/A
- Lancer l'appli
- Se connecter
- Vérifier le bon fonctionnement du menu
> [FEATURE] Ajout d'une barre de navigation

- app/models/user.rb
- db/migrate/20220118094328_add_name_to_users.rb
- db/schema.rb
Actuellement, nous n'enregistrons pas le nom et prénom des utilisateurs, c'est dérangeant pour savoir qui a répondu au feedback. 
Enregistrer le prénom et nom des utilisateurs
> [FEATURE] Enregistrer le prénom et nom des utilisateurs

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/feedbacks.scss
- app/controllers/feedbacks_controller.rb
- app/helpers/application_helper.rb
- app/views/feedbacks/show.html.erb
Actuellement, l'utilisateur ne voit pas le contenu de l'évaluation qu'il a reçue. 
Afficher le contenu de l'évaluation
- On formate le markdown
- Créer une évaluation 
- Répondre avec un autre compte / compte externe
- Consulter l'évaluation et constater que le contenu est présent
> [FEATURE] Pouvoir consulter une évaluation reçue. 

- app/controllers/feedbacks_controller.rb
- app/views/feedbacks/given.html.erb
- app/views/layouts/_navbar.html.erb
- config/routes.rb
L'utilisateur veut pouvoir accèder aux évaluations auxquelles il a répondu
Ajout d'une action `given` au controller des Feedbacks qui retourne les évaluations associées à la foreignKey `given_feedbacks`
> [FEATURE] Voir les évaluations données

- app/controllers/feedbacks_controller.rb
- app/models/feedback.rb
- app/views/feedbacks/show.html.erb
Des erreurs apparaissaient lors de la création d'un feedback
Correction des paramètres manquants
> [FIX] Correction de bug à la création de feedback

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/feedbacks.scss
- app/assets/stylesheets/globals/_colors.scss
- app/controllers/feedbacks_controller.rb
- app/models/feedback.rb
- app/views/feedbacks/given.html.erb
- app/views/feedbacks/index.html.erb
- app/views/feedbacks/show.html.erb
- db/migrate/20220120092459_add_is_filled_to_feedbacks.rb
- db/schema.rb
Création du design de la page index feedback
Utilisation du scss pour améliorer le design
https://pfe-pix-360-pr20.osc-fr1.scalingo.io/users/sign_in
> [FEATURE] Amélioration du design de la page index feedback

- app/views/feedbacks/edit.html.erb
- app/views/feedbacks/given.html.erb
Les liens de l'évaluation données ne fonctionne pas.
- Réparer les liens
- Remplacer un titre anglais en français dans la page d'édition d'évaluation
> [BUGFIX] Changer le lien cassé dans les évaluations données 

- app/assets/stylesheets/feedbacks.scss
- app/assets/stylesheets/navbar.scss
L'accès sur téléphone est difficile
Améliorer le design sur mobile
> [FEATURE] Améliorer le responsive des pages

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/feedbacks.scss
- app/assets/stylesheets/globals/_colors.scss
- app/controllers/feedbacks_controller.rb
- app/views/feedbacks/index.html.erb
- app/views/layouts/application.html.erb
Actuellement, les messages d'erreur ou de succès ne sont pas toujours visibles. C'est dérangeant pour l'utilisateur qui n'a pas de retours ce qu'il a fait.
Mieux gérer les messages flash
> [FEATURE] Améliorer l'usage des messages flash.

- app/controllers/encryption_controller.rb
Nous sommes déconnecter après la création de notre mot de passe, ce qui complique l'utilisation de l'application.
Nous reconnectons l'utilisateur après qu'il ait créé son mot de passe. 
> [FEATURE] Eviter la déconnexion après la création de mot de passe.

- app/assets/stylesheets/feedbacks.scss
- app/views/feedbacks/new.html.erb
- app/views/feedbacks/show.html.erb
Des petites incohérences graphiques sont présentes.
Les résoudre
> [BUGFIX] Améliorations du design des pages feedbacks.

- app/controllers/encryption_controller.rb
- app/views/feedbacks/given.html.erb
- app/views/feedbacks/index.html.erb
- app/views/feedbacks/show.html.erb
Le cookie contenant le mot de passe servant au chiffrement n'est pas bien remplis lors de la création de celui-ci.
Remplir le cookie avec le bon mot de passe.
> [BUGFIX] Faciliter le workflow d'authentification

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/feedbacks.scss
- app/javascript/packs/clipboard.js
- app/views/feedback_mailer/feedback_email.html.erb
- app/views/feedbacks/show.html.erb
- package.json
- yarn.lock
Lorsque l'utilisateur souhaite renvoyer le lien à la personne qu'il souhaite, il est obligé sélectionner le lien et de le copier. Comme le lien est long cela peut-être sujet à des erreurs.
Proposer un bouton permettant de copier le lien. 
- Créer une évaluation
- Cliquer sur le bouton copier le lien
- Constater que le lien est bon
> [FEATURE] Ajouter un bouton pour copier le lien d'une évaluation.

- app/assets/stylesheets/feedbacks.scss
- app/views/feedbacks/given.html.erb
- app/views/feedbacks/index.html.erb
Lorsque l'utilisateur n'a pas reçu d'évaluation la page parait vide et il manque du contexte.
Ajouter du contexte en informant l'utilisateur.
> [FEATURE] Ajout de messages lorsque l'utilisateur n'a pas encore reçu/donné d'évaluation.

- app/assets/stylesheets/feedbacks.scss
- app/views/feedbacks/given.html.erb
- app/views/feedbacks/index.html.erb
L'utilisateur ne peut plus voir la liste de ses évaluations reçues ou données.
Corriger la condition d'affichage
> [BUGFIX] L'utilisateur ne peut plus voir la liste de ses évaluations reçues ou données.

- app/views/feedback_mailer/feedback_email.html.erb
Il n'y a plus de bouton dans les e-mails
Revert la suppression de commentaires qui ont cassé l'e-mail
> [BUGFIX] Réparer le bouton des mails

- app/assets/stylesheets/navbar.scss
- app/views/layouts/_navbar.html.erb
- config/routes.rb
Durant une PR le css gérant le responsive de la navbar a été supprimé.
L'ajouter de nouveau.
Au passage la root url a été fixé. 
> [BUGFIX] Améliorer le navbar sur mobile.

- app/views/feedbacks/edit.html.erb
- app/views/feedbacks/show.html.erb
Lorsque l'utilisateur se rend sur une évaluation il n'a pas de contexte.
Ajouter du contexte en ajoutant : 
- La date de la demande ou d'envoie si elle existe
- Par qui c'est demandé ou par qui c'est remplie
> [FEATURE] Ajouter du contexte dans les évaluations.

- app/assets/stylesheets/feedbacks.scss
- app/views/feedbacks/edit.html.erb
Lorsqu'un utilisateur est en train d'écrire une évaluation, il n'a pas de contexte sur l'application.
Ajouter le logo de Pix 360 quand la personne est externe à l'organisation
> [FEATURE] Ajout du logo pour les personnes externes sur la page de modification d'une évaluation.

- app/controllers/feedbacks_controller.rb
- app/models/feedback.rb
- app/views/feedbacks/_given-feedbacks.html.erb
- app/views/feedbacks/_received-feedbacks.html.erb
- app/views/feedbacks/index.html.erb
- app/views/feedbacks/new.html.erb
- app/views/feedbacks/show.html.erb
- db/migrate/20220126132537_add_respondent_information_to_feedbacks.rb
- db/schema.rb
- test/controllers/feedbacks_controller_test.rb
- test/fixtures/feedbacks.yml
- test/models/feedback_test.rb
L'utilisateur ne sait pas à qui est destiné la demande d'évaluation après l'avoir créé. 
Récupérer les informations et les chiffrer avec le mot de passe dédié au chiffrement. 
> [FEATURE] Récupérer les informations du donneur d'évaluation. 

- app/views/feedbacks/edit.html.erb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/application.html.erb
Certains manquement peuvent causer des problèmes d'accessibilité.
Résoudre les problèmes
> [FEATURE] Améliorer l'accessibilité

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/feedbacks.scss
La PR #56 a ajouté le style des anchor en globale, seulement ça a cassé le design des élements.
Supprimer la solution et faire un style dédié
> [BUGFIX] Enlever le style des balise anchor globale.

- app/assets/stylesheets/navbar.scss
- app/views/layouts/_navbar.html.erb
Actuellement, l'utilisateur ne sait pas rapidement sur quel page il se trouve.
Mettre en évidence dans la navbar le lien où l'utilisateur se trouve
- Naviguer entre les pages et constater que le bon lien est mis en évidence
> [FEATURE] Mettre en évidence le lien sur lequel l'utilisateur se trouve dans la barre de navigation

- app/controllers/feedbacks_controller.rb
L'e-mail envoyé lors de la soumission d'une évaluation contient un lien qui n'est pas correct.
Fixer le lien
> [BUGFIX] Résoudre le problème du lien des e-mails.

- config/environments/production.rb
Le logo ne s'affiche plus dans les e-mails
Ajouter l'host par défaut
> [BUGFIX] Faire en sorte que logo dans les e-mails s'affiche.

- app/assets/stylesheets/navbar.scss
- Les liens de la navbar ne sont plus centrés
- Centrer les liens
> [BUGFIX] Centrer les liens de la navbar

- app/views/feedbacks/new.html.erb
L'autofocus était sur le mail et non le Nom/prenom de l'utilisateur
> [FIX] Autofocus pour la demande de feedback

- app/assets/stylesheets/errors.scss
- app/controllers/errors_controller.rb
- config/routes.rb
Les pages d'erreur n'étaient pas accessible
Ajout des routes
> [FIX] Pages d'erreur inaccessible

- app/assets/stylesheets/application.scss
- app/views/encryption/edit.html.erb
- config/application.rb
- config/locales/devise.fr.yml
- config/locales/fr.yml
Certains messages d'erreurs sont en anglais.
Ajouter une traduction française des messages
> [FEATURE] Ajouter les traductions française des messages d'erreur

- app/views/layouts/application.html.erb
- scalingo.json
> [BUGFIX] Améliorer le titre des pages

- app/views/feedbacks/edit.html.erb
- app/views/feedbacks/show.html.erb
> [BUGFIX] Typo sur la page de rédaction et de réception d'une évaluation

- app/controllers/errors_controller.rb
- app/models/user.rb
Certaines routes ne sont pas accessibles, mais existe toujours.
Supprimer ces routes.
Une requête inutile a été supprimé dans le controlleur errors
> [TECH] Suppression de certaines routes.

- package.json
- yarn.lock
> ci: remove semantic-release

- .github/workflows/cd.yml
> [TECH] Ajouter les dépendances de semanctic-release dans le workflow de CD

- app/controllers/feedbacks_controller.rb
- test/controllers/feedbacks_controller_test.rb
> Refactor to avoid before_action

- app/controllers/feedbacks_controller.rb
- test/controllers/feedbacks_controller_test.rb
> Add authorization to destroy feedback

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- package.json
- yarn.lock
> Update node version

- .github/renovate.json
[Depuis l'ADR](https://github.com/1024pix/pix/blob/f3699bfccbdbb035acdfa757ee1dbfd3cf04bcc0/docs/adr/0039-mise-%C3%A0-jour-des-d%C3%A9pendances.md), nous n'avons pas ajouté la config renovate qui va bien. 
Ajouter la config
> _Des infos supplémentaires, trucs et astuces ?_
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._
> [TECH] Ajouter la config pour renovate

- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/production.rb
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._
> _Des infos supplémentaires, trucs et astuces ?_
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._
> [BUGFIX] Les traces ne sont pas au format JSON en production

- .github/workflows/release.yml
L'action release n'a pas les droits pour pusher sur main
Utiliser un PAT
> [TECH] Utiliser un token qui permet à l'action release de pusher
